### PR TITLE
Blog app - controllers specs

### PR DESCRIPTION
**Pull request by wale-prog**
In this pull request, I gave implemented the following:
- Created a request spec file for all the controllers
- Wrote tests to ensure that for each action the response status was correct, the template was rendered correctly, and the response body includes the correct placeholder text.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @wale-prog,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are green  ✅.
- PR is very well made 👌.
- The readme file is good.

## Required Changes ♻️
_Check the comments under the review._

- Hello and nice job adding the tests but there are some tests that fail due to the wrong argument provided in your test cases.

Capture d’écran 2022-09-20 121825
Capture d’écran 2022-09-20 121934


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wale-prog** [comment]
Thanks for the feedback, but those errors did not have anything to do with the requirements for this project. This pull request is about controller-spec and all the tests passed. I believe it should be optional.

**Review by julie-ify — APPROVED** [review]
Hi @wale-prog,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wale-prog** [comment]
Thank you for the review.

**Pull request merged**
